location               = "uaenorth"
az_resource_group_name = "test-examples"
location_abbreviation  = "un"
project                = "mdp"
az_subnet_cidr         = "10.0.1.0/24,10.0.2.0/24, 10.0.3.0/24"
az_vnet_name           = "vnet-dev-un-001"
az_subnet_sequence     = "001"
environment            = "test"
az_nsg_id              = "/subscriptions/xxxx-xxxx/resourceGroups/test-examples/providers/Microsoft.Network/networkSecurityGroups/nsg-example-009"
az_route_table_id      = "/subscriptions/xxxx-xxxx/resourceGroups/test-examples/providers/Microsoft.Network/routeTables/route-example-route-table"

